import type { TraceState } from '../types/trace';
import type { VisualEvent } from '../visualization/engine/visualEvents';
import type { AlgorithmFamily } from '../visualization/engine/algorithmSemantics';
import { displayValue, isPlainObject, stableStringify } from '../utils/value';

type ArraySnapshot={ $arrayId:string; values:unknown[]; $type?:string };
type MapSnapshot={ $mapId:string; entries:Array<{key:unknown;value:unknown}>; $type?:string };
type CollectionSnapshot={ $collectionId:string; values:unknown[]; $kind?:string; $type?:string };
const isArray=(v:unknown):v is ArraySnapshot=>isPlainObject(v)&&typeof v.$arrayId==='string'&&Array.isArray(v.values);
const isMap=(v:unknown):v is MapSnapshot=>isPlainObject(v)&&typeof v.$mapId==='string'&&Array.isArray(v.entries);
const isCollection=(v:unknown):v is CollectionSnapshot=>isPlainObject(v)&&typeof v.$collectionId==='string'&&Array.isArray(v.values);
function numeric(vars:Record<string,unknown>,names:string[]):number|undefined{for(const n of names)if(typeof vars[n]==='number'&&Number.isFinite(vars[n]))return vars[n] as number;return undefined;}
function op(events:VisualEvent[]){for(const e of events){if(e.type==='swap')return 'SWAP';if(e.type==='compare')return 'COMPARE';if(e.type==='insert')return 'INSERT';if(e.type==='remove')return 'REMOVE';if(e.type==='update')return 'UPDATE';if(e.type==='move')return 'MOVE';if(e.type==='traverse')return 'TRAVERSE';}return 'OBSERVE';}
function DeepPattern({family,state,previous,visualEvents}:{family:AlgorithmFamily;state?:TraceState;previous?:TraceState;visualEvents:VisualEvent[]}){
 const vars=state?.variables??{};const arrays=Object.entries(state?.arrays??{}).filter(([,v])=>isArray(v)) as [string,ArraySnapshot][];const collections=Object.entries(state?.dataStructures??{}).filter(([,v])=>isCollection(v)) as [string,CollectionSnapshot][];const first=arrays[0];const current=vars.current??vars.node??vars.u??vars.vertex??vars.currentNode;const next=vars.next??vars.neighbor??vars.v??vars.to??vars.nextNode;const index=numeric(vars,['i','j','index','idx','pos','currentIndex']);const opName=op(visualEvents);
 if(family==='dynamic-programming'){const matrix=arrays.find(([,v])=>v.values.some(x=>Array.isArray(x)));if(matrix){const rows=matrix[1].values.filter(Array.isArray) as unknown[][];const r=numeric(vars,['row','i','r']);const c=numeric(vars,['col','j','c']);const oldArray=previous?.arrays?.[matrix[1].$arrayId];const old=isArray(oldArray)?oldArray.values:undefined;return <div className="yv-pattern-view"><div className="yv-pattern-head"><span>DP · STATE TABLE</span><b>{opName}</b></div><div className="yv-deep-grid">{rows.map((row,ri)=>row.map((v,ci)=>{const oldCell=Array.isArray(old?.[ri])?old[ri][ci]:undefined;const changed=stableStringify(oldCell)!==stableStringify(v);return <div key={ri+'-'+ci} className={['yv-deep-grid-cell',ri===r&&ci===c?'yv-deep-grid-active':'',changed?'yv-deep-grid-changed':''].filter(Boolean).join(' ')}><b>{displayValue(v)}</b><small>{ri},{ci}</small></div>}))}</div><div className="yv-pattern-meta">{r!==undefined&&<span><b>ROW</b> {r}</span>}{c!==undefined&&<span><b>COL</b> {c}</span>}<span>STATE → TRANSITION → UPDATE</span></div></div>;}if(first)return <div className="yv-pattern-view"><div className="yv-pattern-head"><span>DP · STATE ARRAY</span><b>{opName}</b></div><div className="yv-pattern-array">{first[1].values.map((v,k)=><div className={k===index?'yv-pattern-cell yv-pattern-current':'yv-pattern-cell'} key={k}><b>{displayValue(v)}</b><small>{k}</small></div>)}</div><div className="yv-pattern-meta"><span>ACTIVE STATE {index??'—'}</span><span>STATE → TRANSITION → UPDATE</span></div></div>;}
 if(family==='queue-bfs'||family==='dfs'||family==='graph-traversal'||family==='shortest-path'){const queue=collections.find(([,v])=>v.$kind==='queue'||v.$kind==='deque')??collections[0];const visited=collections.filter(([,v])=>v.$kind==='set');const dist=arrays.find(([n])=>/dist|distance/i.test(n));return <div className="yv-pattern-view"><div className="yv-pattern-head"><span>{family==='queue-bfs'?'BFS · FRONTIER':family==='dfs'?'DFS · CALL DEPTH':family==='shortest-path'?'SHORTEST PATH · RELAXATION':'GRAPH TRAVERSAL'}</span><b>{opName}</b></div>{queue&&<><div className="yv-pattern-row-label">FRONTIER / QUEUE</div><div className="yv-pattern-queue">{queue[1].values.map((v,k)=><div className={k===0?'yv-pattern-queue-active':'yv-pattern-queue-cell'} key={k}>{displayValue(v)}</div>)}</div></>}{visited.map(([name,v])=><div key={name}><div className="yv-pattern-row-label">VISITED · {name}</div><div className="yv-pattern-set">{v.values.map((v,k)=><span className="yv-pattern-set-item" key={k}>{displayValue(v)}</span>)}</div></div>)}{dist&&<><div className="yv-pattern-row-label">DISTANCE</div><div className="yv-pattern-array">{dist[1].values.map((v,k)=><div className={k===current||k===next?'yv-pattern-cell yv-pattern-current':'yv-pattern-cell'} key={k}><b>{displayValue(v)}</b><small>{k}</small></div>)}</div></>}<div className="yv-pattern-meta">{current!==undefined&&<span><b>CURRENT</b> {displayValue(current)}</span>}{next!==undefined&&<span><b>NEXT</b> {displayValue(next)}</span>}{family==='dfs'&&<span><b>DEPTH</b> {(state?.callStack??[]).length}</span>}<span>{visited.reduce((n,[,v])=>n+v.values.length,0)} visited</span></div></div>;}
 if(family==='backtracking'){const frames=state?.callStack??[];const choice=vars.choice??vars.candidate??vars.current??vars.i??vars.index;return <div className="yv-pattern-view"><div className="yv-pattern-head"><span>BACKTRACKING · DECISION PATH</span><b>{opName}</b></div><div className="yv-backtrack-path">{frames.map((frame,k)=><div className={k===frames.length-1?'yv-backtrack-node yv-backtrack-active':'yv-backtrack-node'} key={k}><small>{k}</small><b>{String(frame)}</b></div>)}</div><div className="yv-pattern-meta">{choice!==undefined&&<span><b>CHOICE</b> {displayValue(choice)}</span>}<span><b>DEPTH</b> {frames.length}</span><span>CHOOSE → EXPLORE → UNCHOOSE</span></div></div>;}
 if(family==='recursion'||family==='array-scan'){const frames=state?.callStack??[];return <div className="yv-pattern-view"><div className="yv-pattern-head"><span>{family==='recursion'?'RECURSION · CALL STACK':'LINEAR SCAN · CURRENT INDEX'}</span><b>{opName}</b></div>{family==='recursion'&&<div className="yv-recursion-stack">{frames.map((f,k)=><div className={k===frames.length-1?'yv-recursion-frame yv-recursion-active':'yv-recursion-frame'} key={k}><small>{k}</small><b>{String(f)}</b></div>)}</div>}{first&&<div className="yv-pattern-array">{first[1].values.map((v,k)=><div className={k===index?'yv-pattern-cell yv-pattern-current':'yv-pattern-cell'} key={k}><b>{displayValue(v)}</b><small>{k}</small></div>)}</div>}<div className="yv-pattern-meta">{index!==undefined&&<span><b>INDEX</b> {index}</span>}<span><b>DEPTH</b> {frames.length}</span></div></div>;}
 if(family==='linked-list'||family==='tree-traversal'||family==='trie'){const objects=Object.entries(state?.objects??{}).slice(0,16);return <div className="yv-pattern-view"><div className="yv-pattern-head"><span>{family==='linked-list'?'LINKED LIST · POINTER WALK':family==='tree-traversal'?'TREE · NODE WALK':'TRIE · CHARACTER WALK'}</span><b>{opName}</b></div><div className="yv-object-walk">{objects.map(([id,obj],k)=>{const record=isPlainObject(obj)?obj:{};return <div className={String(current)===id?'yv-object-walk-node yv-object-walk-active':'yv-object-walk-node'} key={id}><span>{k}</span><b>{String(record.$type??record.value??id)}</b>{record.next!==undefined&&<small>→ {displayValue(record.next)}</small>}</div>})}</div><div className="yv-pattern-meta">{current!==undefined&&<span><b>CURRENT</b> {displayValue(current)}</span>}<span>{objects.length} runtime object(s)</span><span>{family==='trie'?'MATCH → FOLLOW CHILD':'VISIT → FOLLOW LINK'}</span></div></div>;}
 return null;
}
export function AlgorithmPatternView({family,state,previous,visualEvents}:{family:AlgorithmFamily;state?:TraceState;previous?:TraceState;visualEvents:VisualEvent[]}){
 const vars=state?.variables??{}; const entries=Object.entries(state?.arrays??{}).filter(([,v])=>isArray(v)) as [string,ArraySnapshot][]; const first=entries[0]; const sequence=state?.sequence??0;
 const left=numeric(vars,['left','start','l','windowStart','leftIndex','lo']); const right=numeric(vars,['right','end','r','windowEnd','rightIndex','hi']); const i=numeric(vars,['i','idx','index','pos','currentIndex']); const j=numeric(vars,['j','secondIndex']); const sum=numeric(vars,['sum','windowSum','currentSum','runningSum','prefixSum','prefix']);
 if(family==='sliding-window'||family==='two-pointer'){
  if(!first)return null; const [name,array]=first; const a=family==='sliding-window'?(left??i):(numeric(vars,['i','left','l','a'])??i); const b=family==='two-pointer'?(numeric(vars,['j','right','r','b'])??j):(right??j); const previousLeft=numeric(previous?.variables??{},['left','start','l','windowStart','leftIndex','lo'])??numeric(previous?.variables??{},['i','idx','index','pos']); const previousRight=numeric(previous?.variables??{},['right','end','r','windowEnd','rightIndex','hi'])??numeric(previous?.variables??{},['j','secondIndex']);
  const changedBoundary=(previousLeft!==undefined&&a!==undefined&&previousLeft!==a)||(previousRight!==undefined&&b!==undefined&&previousRight!==b); const phase=op(visualEvents); const entered=family==='sliding-window'&&b!==undefined&&previousRight!==undefined&&b>previousRight?b:undefined; const leftWindow=family==='sliding-window'&&a!==undefined&&previousLeft!==undefined&&a>previousLeft?previousLeft:undefined;
  return <div className="yv-pattern-view" data-array={name}><div className="yv-pattern-head"><span>{family==='sliding-window'?'SLIDING WINDOW':'TWO POINTER'}</span><b>{phase}</b></div><div className="yv-pattern-array">{array.values.map((v,index)=>{const inWindow=a!==undefined&&b!==undefined&&index>=Math.min(a,b)&&index<=Math.max(a,b);const isA=index===a;const isB=index===b;const touched=visualEvents.some(e=>e.type==='compare'?e.targets.some(t=>t.structureId===array.$arrayId&&t.index===index):e.type==='highlight'?e.target.structureId===array.$arrayId&&e.target.index===index:false);return <div key={index+'-'+(changedBoundary&&(isA||isB)?sequence:0)} className={['yv-pattern-cell',inWindow?'yv-pattern-in-window':'',isA?'yv-pattern-left':'',isB?'yv-pattern-right':'',touched?'yv-pattern-touched':''].filter(Boolean).join(' ')}><div className="yv-pattern-pointer">{isA?'L':''}{isA&&isB?' / ':''}{isB?'R':''}</div><b>{displayValue(v)}</b><small>{index}</small></div>})}</div><div className="yv-pattern-meta">{a!==undefined&&<span><b>{family==='sliding-window'?'LEFT':'A'}</b> {a}</span>}{b!==undefined&&<span><b>{family==='sliding-window'?'RIGHT':'B'}</b> {b}</span>}{sum!==undefined&&<span><b>{family==='sliding-window'?'WINDOW':'RUNNING'}</b> {sum}</span>}<span>{a!==undefined&&b!==undefined?Math.max(0,Math.abs(b-a)+1)+' active element(s)':'Waiting for pointer values'}</span>{entered!==undefined&&<span><b>ENTERED</b> {displayValue(array.values[entered])}</span>}{leftWindow!==undefined&&<span><b>LEFT WINDOW</b> {displayValue(array.values[leftWindow])}</span>}</div></div>;
 }
 if(family==='prefix-sum'){
  if(!first)return null; const [name,array]=first; const prefixEntry=entries.find(([n])=>/prefix|presum|running|sum/i.test(n)&&n!==name); const index=i??right; const prefixValues=prefixEntry?.[1].values; const touched=visualEvents.flatMap(e=>e.type==='update'?[e.target]:e.type==='compare'?e.targets:[]).filter(t=>t.structureId===array.$arrayId).map(t=>t.index);
  return <div className="yv-pattern-view"><div className="yv-pattern-head"><span>PREFIX SUM</span><b>{op(visualEvents)}</b></div><div className="yv-pattern-array">{array.values.map((v,k)=><div key={k} className={['yv-pattern-cell',k===index?'yv-pattern-current':'',touched.includes(k)?'yv-pattern-touched':''].filter(Boolean).join(' ')}><b>{displayValue(v)}</b><small>{k}</small></div>)}</div>{prefixValues&&<><div className="yv-pattern-row-label">PREFIX ARRAY · {prefixEntry?.[0]}</div><div className="yv-pattern-array">{prefixValues.map((v,k)=><div key={k} className={['yv-pattern-cell',k===index?'yv-pattern-current':''].filter(Boolean).join(' ')}><b>{displayValue(v)}</b><small>{k}</small></div>)}</div></>}<div className="yv-pattern-meta">{index!==undefined&&<span><b>INDEX</b> {index}</span>}{sum!==undefined&&<span><b>ACCUMULATED</b> {sum}</span>}<span>{name}</span></div></div>;
 }
 if(family==='monotonic-stack'||family==='stack'||family==='heap'){
  const collection=Object.entries(state?.dataStructures??{}).find(([,v])=>isCollection(v)) as [string,CollectionSnapshot]|undefined; if(!collection)return null; const [name,value]=collection; const isHeap=family==='heap'; const vals=value.values;
  return <div className="yv-pattern-view"><div className="yv-pattern-head"><span>{isHeap?'HEAP STATE':family==='monotonic-stack'?'MONOTONIC STACK':'STACK STATE'}</span><b>{op(visualEvents)}</b></div><>{isHeap?<div className="yv-pattern-heap-tree">{Array.from({length:Math.ceil(Math.log2(vals.length+1))},(_,level)=>vals.slice(2**level-1,Math.min(vals.length,2**(level+1)-1))).map((levelValues,level)=><div className="yv-pattern-heap-level" key={level}>{levelValues.map((v,k)=>{const index=2**level-1+k;return <div key={index} className={['yv-pattern-structure-cell',index===0?'yv-pattern-current':''].filter(Boolean).join(' ')}><b>{displayValue(v)}</b><small>idx {index}</small></div>})}</div>)}</div>:<div className={family==='monotonic-stack'?'yv-pattern-mono-stack':'yv-pattern-stack'}>{vals.map((v,k)=>{const top=k===vals.length-1;return <div key={k} className={['yv-pattern-structure-cell',top?'yv-pattern-current':''].filter(Boolean).join(' ')}><b>{displayValue(v)}</b><small>{top?'TOP':k}</small></div>})}{!vals.length&&<span className="yv-empty">Empty structure</span>}</div>}</><div className="yv-pattern-meta"><span>{name}</span><span>{vals.length} elements</span>{vals.length>0&&<span><b>TOP</b> {displayValue(vals[vals.length-1])}</span>}</div></div>;
 }
 if(family==='hashing'){
  const mapEntry=Object.entries(state?.dataStructures??{}).find(([,v])=>isMap(v)) as [string,MapSnapshot]|undefined; const mapArray=entries.find(([n])=>/freq|count|map/i.test(n)); if(!mapEntry&&!mapArray)return null;
  const pairs=mapEntry?mapEntry[1].entries.map(e=>[e.key,e.value] as const):mapArray![1].values.map((v,k)=>[k,v] as const); const currentKey=vars.key??vars.num??vars.value??vars.ch; const found=pairs.find(([k])=>String(k)===String(currentKey));
  return <div className="yv-pattern-view"><div className="yv-pattern-head"><span>HASH LOOKUP / FREQUENCY</span><b>{op(visualEvents)}</b></div><div className="yv-pattern-map">{pairs.slice(0,30).map(([k,v],idx)=><div key={idx} className={currentKey!==undefined&&String(k)===String(currentKey)?'yv-pattern-map-entry yv-pattern-current':'yv-pattern-map-entry'}><span>{displayValue(k)}</span><b>{displayValue(v)}</b></div>)}</div><div className="yv-pattern-meta">{currentKey!==undefined&&<span><b>KEY</b> {displayValue(currentKey)}</span>}{found&&<span><b>VALUE</b> {displayValue(found[1])}</span>}<span>{pairs.length} entries</span></div></div>;
 }
 if(family==='shortest-path'){
  const distEntry=entries.find(([n])=>/dist|distance/i.test(n)); const currentNode=numeric(vars,['u','node','currentNode','vertex','from']); const nextNode=numeric(vars,['v','to','neighbor','nextNode']); const distances=distEntry?.[1];
  if(!distances)return null;
  return <div className="yv-pattern-view"><div className="yv-pattern-head"><span>SHORTEST PATH · DISTANCES</span><b>{op(visualEvents)}</b></div><div className="yv-pattern-array">{distances.values.map((v,k)=><div key={k} className={k===currentNode||k===nextNode?'yv-pattern-cell yv-pattern-current':'yv-pattern-cell'}><b>{displayValue(v)}</b><small>node {k}</small></div>)}</div><div className="yv-pattern-meta">{currentNode!==undefined&&<span><b>FROM</b> {currentNode}</span>}{nextNode!==undefined&&<span><b>TO</b> {nextNode}</span>}<span>{distEntry[0]}</span><span>Distance state from runtime trace</span></div></div>;
 }
 if(family==='greedy'){
  const candidate=numeric(vars,['i','index','idx','candidate','currentIndex','pos']); const selected=vars.selected??vars.best??vars.answer??vars.current; const arr=first;
  return <div className="yv-pattern-view"><div className="yv-pattern-head"><span>GREEDY CHOICE</span><b>{op(visualEvents)}</b></div>{arr&&<div className="yv-pattern-array">{arr[1].values.map((v,k)=><div key={k} className={k===candidate?'yv-pattern-cell yv-pattern-current':'yv-pattern-cell'}><b>{displayValue(v)}</b><small>{k}</small></div>)}</div>}<div className="yv-pattern-meta">{candidate!==undefined&&<span><b>CANDIDATE</b> {candidate}</span>}{selected!==undefined&&<span><b>BEST / SELECTED</b> {displayValue(selected)}</span>}<span>Candidate → decision → committed state</span></div></div>;
 }
 return <DeepPattern family={family} state={state} previous={previous} visualEvents={visualEvents}/>;
}